version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/fastapi-app
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/fastapi-app/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: devops/script/start_application.sh
      timeout: 300
      runas: ubuntu
