# appspec.yml
version: 0.0
os: linux
files:
  - source: /src/
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - file
      - directory
  - object: /var/www/html/data/
    pattern: "**"
    mode: 777
    type:
      - directory
hooks:
  BeforeInstall:
    - location: devops/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: devops/scripts/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: devops/scripts/start_application.sh
      timeout: 300
      runas: root